Fix str_split & close entity nearby other entity
M6Web/DraftjsBundle pull request #11
Opened 2017-03-28 08:22 UTC by Doss

2017-03-28 08:54 UTC, oltodo commented on Renderer/Content/ContentRenderer.php
> -        $chars = str_split($text);
Et [mb_split](http://php.net/manual/fr/function.mb-split.php) ?

2017-03-28 09:21 UTC, Doss commented on Renderer/Content/ContentRenderer.php
> -        $chars = str_split($text);
J'ai fixé avec preg_split, mb_split ne permettait pas de simuler un str_split.

2017-03-28 10:01 UTC, jdohuutin approved these changes

2017-03-28 10:01 UTC, jdohuutin commented on Renderer/Content/ContentRenderer.php
> +                if (!is_null($previousEntity) && $entityIndex !== $previousEntity) {
:+1:

2017-03-28 16:07 UTC, yohannpoli commented on Renderer/Content/ContentRenderer.php
> +                if (!is_null($previousEntity) && $entityIndex !== $previousEntity) {
\0/

2017-03-28 18:58 UTC, yohannpoli approved these changes

2017-03-29 07:47 UTC, oltodo approved these changes

2017-03-29 07:51 UTC, oltodo requested changes
Maybe test it

2017-03-29 07:52 UTC, oltodo commented on Renderer/Content/ContentRenderer.php
> +
A supprimer

2017-03-29 13:04 UTC, oltodo approved these changes

2017-03-29 13:05 UTC, merged