Refactoring
M6Web/DraftjsBundle pull request #2
Opened 2017-02-07 15:38 UTC by yohannpoli

2017-02-08 20:41 UTC, yohannpoli commented
Note à moi même, il faut vérifier le setter de l'entity dans la class CharacterMetadata (est-ce c'est une ref objet ou bien l'index dans l'entityMap)

2017-02-13 15:05 UTC, jdohuutin commented on Resources/config/services.yml
> +            - [setTemplate, ['M6WebDraftjsBundle:Block:default.html.twig']]
Autant définir en dur le template à utiliser directement dans le renderder. (Comme il n'est pas possible d'override `setTemplate`).

2017-02-13 16:24 UTC, jdohuutin approved these changes

2017-02-15 08:44 UTC, oltodo requested changes

2017-02-15 08:44 UTC, oltodo commented on Converter/ContentStateConverter.php
>          $createEntityFromRaw = function ($entities, $rawEntity) {
Tu ne peux pas simplifier le tout avec simple un `array_map` ?

```php
return array_map(function ($rawEntity) {
  $type = $rawEntity['type'];
  $mutability = $rawEntity['mutability'];
  $data = $rawEntity['data'];

  return new DraftEntity($type, $mutability, $data);
}, $entityMap);

2017-02-15 08:44 UTC, oltodo commented on DependencyInjection/Compiler/BlockEntityRendererPass.php
> +        $guesser = 'm6_web_draftjs.block_entity_guesser';
Qu'est ce qui est utilisé en général comme préfix des bundles de l'orga ? `m6_web_` ou `m6web_` ?

2017-02-15 08:44 UTC, oltodo commented on Builder/HtmlBuilder.php
> +            $output .= $renderer->render($iterator, $entities);
Il serait très intéressant de lancer une exception si l'itérateur n'a pas avancé à la suite du `render`

2017-02-15 08:47 UTC, yohannpoli commented on Builder/HtmlBuilder.php
> +            $output .= $renderer->render($iterator, $entities);
oui, je vais voir ça

2017-02-15 08:48 UTC, yohannpoli commented on DependencyInjection/Compiler/BlockEntityRendererPass.php
> +        $guesser = 'm6_web_draftjs.block_entity_guesser';
c'est iso M6Web à priori

2017-02-15 12:55 UTC, oltodo approved these changes

2017-02-15 15:19 UTC, merged